### ISSUE TITLE
Fix inference_handler error path error

### ISSUE THREAD

**Issue by toddnief** [uchicago-dsi/good-food-purchasing#138]

**Comment by toddnief** [comment]
Traceback (most recent call last):
  File "/home/tnief/1-Projects/good-food-purchasing/scripts/train.py", line 371, in <module>
    output_sheet = inference_handler(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/tnief/1-Projects/good-food-purchasing/src/cgfp/inference/inference.py", line 246, in inference_handler
    save_output(df_formatted, output_filename, save_dir)
  File "/home/tnief/1-Projects/good-food-purchasing/src/cgfp/inference/inference.py", line 159, in save_output
    output_path = filename.rstrip(".xlsx") + "_classified.xlsx"
                  ^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'rstrip'
